/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _i1;
import 'package:serverpod_client/serverpod_client.dart' as _i2;
import 'dart:async' as _i3;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _i4;
import 'package:kvitter_client/src/protocol/room_chat.dart' as _i5;
import 'package:kvitter_client/src/protocol/chat_message.dart' as _i6;
import 'package:kvitter_client/src/protocol/chat_user.dart' as _i7;
import 'package:kvitter_client/src/protocol/private_chat.dart' as _i8;
import 'dart:typed_data' as _i9;
import 'protocol.dart' as _i10;

/// By extending [AppleIdpBaseEndpoint], the Apple identity provider endpoints
/// are made available on the server and enable the corresponding sign-in widget
/// on the client.
/// {@category Endpoint}
class EndpointAppleIdp extends _i1.EndpointAppleIdpBase {
  EndpointAppleIdp(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'appleIdp';

  /// Signs in a user with their Apple account.
  ///
  /// If no user exists yet linked to the Apple-provided identifier, a new one
  /// will be created (without any `Scope`s). Further their provided name and
  /// email (if any) will be used for the `UserProfile` which will be linked to
  /// their `AuthUser`.
  ///
  /// Returns a session for the user upon successful login.
  @override
  _i3.Future<_i4.AuthSuccess> login({
    required String identityToken,
    required String authorizationCode,
    required bool isNativeApplePlatformSignIn,
    String? firstName,
    String? lastName,
  }) => caller.callServerEndpoint<_i4.AuthSuccess>(
    'appleIdp',
    'login',
    {
      'identityToken': identityToken,
      'authorizationCode': authorizationCode,
      'isNativeApplePlatformSignIn': isNativeApplePlatformSignIn,
      'firstName': firstName,
      'lastName': lastName,
    },
  );

  @override
  _i3.Future<bool> hasAccount() => caller.callServerEndpoint<bool>(
    'appleIdp',
    'hasAccount',
    {},
  );
}

/// By extending [GoogleIdpBaseEndpoint], the Google identity provider endpoints
/// are made available on the server and enable the corresponding sign-in widget
/// on the client.
/// {@category Endpoint}
class EndpointGoogleIdp extends _i1.EndpointGoogleIdpBase {
  EndpointGoogleIdp(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'googleIdp';

  /// Validates a Google ID token and either logs in the associated user or
  /// creates a new user account if the Google account ID is not yet known.
  ///
  /// If a new user is created an associated [UserProfile] is also created.
  @override
  _i3.Future<_i4.AuthSuccess> login({
    required String idToken,
    required String? accessToken,
  }) => caller.callServerEndpoint<_i4.AuthSuccess>(
    'googleIdp',
    'login',
    {
      'idToken': idToken,
      'accessToken': accessToken,
    },
  );

  @override
  _i3.Future<bool> hasAccount() => caller.callServerEndpoint<bool>(
    'googleIdp',
    'hasAccount',
    {},
  );
}

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _i4.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _i3.Future<_i4.AuthSuccess> refreshAccessToken({
    required String refreshToken,
  }) => caller.callServerEndpoint<_i4.AuthSuccess>(
    'jwtRefresh',
    'refreshAccessToken',
    {'refreshToken': refreshToken},
    authenticated: false,
  );
}

/// {@category Endpoint}
class EndpointChat extends _i2.EndpointRef {
  EndpointChat(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'chat';

  _i3.Future<_i5.RoomChat?> getChat(String chatId) =>
      caller.callServerEndpoint<_i5.RoomChat?>(
        'chat',
        'getChat',
        {'chatId': chatId},
      );

  _i3.Future<List<_i5.RoomChat>> getOpenChats(
    String countryCode,
    bool isDebug,
  ) => caller.callServerEndpoint<List<_i5.RoomChat>>(
    'chat',
    'getOpenChats',
    {
      'countryCode': countryCode,
      'isDebug': isDebug,
    },
  );

  _i3.Future<List<_i6.ChatMessage>> getInitialMessages(
    String chatId,
    bool isPrivate,
  ) => caller.callServerEndpoint<List<_i6.ChatMessage>>(
    'chat',
    'getInitialMessages',
    {
      'chatId': chatId,
      'isPrivate': isPrivate,
    },
  );

  _i3.Future<List<_i6.ChatMessage>> getMoreMessages(
    String chatId,
    bool isPrivate,
    DateTime before,
  ) => caller.callServerEndpoint<List<_i6.ChatMessage>>(
    'chat',
    'getMoreMessages',
    {
      'chatId': chatId,
      'isPrivate': isPrivate,
      'before': before,
    },
  );

  _i3.Future<_i6.ChatMessage> postMessage(_i6.ChatMessage message) =>
      caller.callServerEndpoint<_i6.ChatMessage>(
        'chat',
        'postMessage',
        {'message': message},
      );

  _i3.Future<void> postFeedback(
    String feedback,
    String createdByName,
    String countryCode,
    String countryName,
  ) => caller.callServerEndpoint<void>(
    'chat',
    'postFeedback',
    {
      'feedback': feedback,
      'createdByName': createdByName,
      'countryCode': countryCode,
      'countryName': countryName,
    },
  );

  _i3.Future<void> reduceCredits(
    String userId,
    int amount,
  ) => caller.callServerEndpoint<void>(
    'chat',
    'reduceCredits',
    {
      'userId': userId,
      'amount': amount,
    },
  );

  _i3.Future<void> increaseCredits(
    String userId,
    int amount,
  ) => caller.callServerEndpoint<void>(
    'chat',
    'increaseCredits',
    {
      'userId': userId,
      'amount': amount,
    },
  );
}

/// Provides presence (online users) and messaging infrastructure.
///
/// Presence is driven by [UserEndpoint.setActive] (sets [ChatUser.presence]
/// to `true`) and [UserEndpoint.logout] (sets it to `false`).  The Flutter
/// client polls [getOnlineUsers] on a periodic timer.  This polling-based
/// approach is the planned starting implementation and can be upgraded to a
/// WebSocket stream later using Serverpod 3.x's `Stream<T>` return-type
/// pattern.
/// {@category Endpoint}
class EndpointMessaging extends _i2.EndpointRef {
  EndpointMessaging(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'messaging';

  /// Returns all users whose [ChatUser.presence] field is `true`.
  ///
  /// Callers can optionally filter by [countryCode] to retrieve only users
  /// in a specific country, or pass `null` / an empty string to get all
  /// online users.
  _i3.Future<List<_i7.ChatUser>> getOnlineUsers({String? countryCode}) =>
      caller.callServerEndpoint<List<_i7.ChatUser>>(
        'messaging',
        'getOnlineUsers',
        {'countryCode': countryCode},
      );

  /// Returns the total number of users currently online.
  _i3.Future<int> getOnlineUserCount() => caller.callServerEndpoint<int>(
    'messaging',
    'getOnlineUserCount',
    {},
  );

  /// Marks users as offline if they have not been active within [staleMinutes]
  /// minutes.  Intended to be called from a scheduled [FutureCall] so that
  /// presence stays accurate even when a client disconnects without calling
  /// [UserEndpoint.logout].
  _i3.Future<void> cleanUpStalePresence({required int staleMinutes}) =>
      caller.callServerEndpoint<void>(
        'messaging',
        'cleanUpStalePresence',
        {'staleMinutes': staleMinutes},
      );
}

/// {@category Endpoint}
class EndpointModeration extends _i2.EndpointRef {
  EndpointModeration(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'moderation';

  _i3.Future<void> blockUser(String targetUserId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'blockUser',
        {'targetUserId': targetUserId},
      );

  _i3.Future<void> unblockUser(String targetUserId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'unblockUser',
        {'targetUserId': targetUserId},
      );

  _i3.Future<void> reportMessage(
    String messageId,
    String messageText,
    DateTime messageCreated,
    String messageCreatedBy,
    int messageCreatedByGender,
    String messageCreatedByCountryCode,
    String messageCreatedByImageUrl,
    String messageCreatedByDisplayName,
  ) => caller.callServerEndpoint<void>(
    'moderation',
    'reportMessage',
    {
      'messageId': messageId,
      'messageText': messageText,
      'messageCreated': messageCreated,
      'messageCreatedBy': messageCreatedBy,
      'messageCreatedByGender': messageCreatedByGender,
      'messageCreatedByCountryCode': messageCreatedByCountryCode,
      'messageCreatedByImageUrl': messageCreatedByImageUrl,
      'messageCreatedByDisplayName': messageCreatedByDisplayName,
    },
  );

  _i3.Future<void> reportInappropriateImage(String reportedUserId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'reportInappropriateImage',
        {'reportedUserId': reportedUserId},
      );

  _i3.Future<void> reportBot(String reportedUserId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'reportBot',
        {'reportedUserId': reportedUserId},
      );

  _i3.Future<void> reportHatefulLanguage(String reportedUserId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'reportHatefulLanguage',
        {'reportedUserId': reportedUserId},
      );

  _i3.Future<void> approveImage(String userId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'approveImage',
        {'userId': userId},
      );

  _i3.Future<void> rejectImage(String userId) =>
      caller.callServerEndpoint<void>(
        'moderation',
        'rejectImage',
        {'userId': userId},
      );

  _i3.Future<List<_i7.ChatUser>> getUnapprovedImages() =>
      caller.callServerEndpoint<List<_i7.ChatUser>>(
        'moderation',
        'getUnapprovedImages',
        {},
      );
}

/// {@category Endpoint}
class EndpointPrivateChat extends _i2.EndpointRef {
  EndpointPrivateChat(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'privateChat';

  _i3.Future<_i8.PrivateChat?> createPrivateChat(
    String otherUserId,
    String initialMessage,
    String myName,
    int myGender,
    String myPictureData,
    String otherName,
    int otherGender,
    String otherPictureData,
  ) => caller.callServerEndpoint<_i8.PrivateChat?>(
    'privateChat',
    'createPrivateChat',
    {
      'otherUserId': otherUserId,
      'initialMessage': initialMessage,
      'myName': myName,
      'myGender': myGender,
      'myPictureData': myPictureData,
      'otherName': otherName,
      'otherGender': otherGender,
      'otherPictureData': otherPictureData,
    },
  );

  _i3.Future<bool> isPrivateChatAvailable(String otherUserId) =>
      caller.callServerEndpoint<bool>(
        'privateChat',
        'isPrivateChatAvailable',
        {'otherUserId': otherUserId},
      );

  _i3.Future<void> leavePrivateChat(String chatId) =>
      caller.callServerEndpoint<void>(
        'privateChat',
        'leavePrivateChat',
        {'chatId': chatId},
      );

  _i3.Future<void> setLastMessageRead(String chatId) =>
      caller.callServerEndpoint<void>(
        'privateChat',
        'setLastMessageRead',
        {'chatId': chatId},
      );

  _i3.Future<void> leaveAllPrivateChats() => caller.callServerEndpoint<void>(
    'privateChat',
    'leaveAllPrivateChats',
    {},
  );

  _i3.Future<List<_i8.PrivateChat>> getPrivateChats() =>
      caller.callServerEndpoint<List<_i8.PrivateChat>>(
        'privateChat',
        'getPrivateChats',
        {},
      );

  _i3.Future<_i8.PrivateChat?> getPrivateChatWithUser(String otherUserId) =>
      caller.callServerEndpoint<_i8.PrivateChat?>(
        'privateChat',
        'getPrivateChatWithUser',
        {'otherUserId': otherUserId},
      );
}

/// {@category Endpoint}
class EndpointStorage extends _i2.EndpointRef {
  EndpointStorage(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'storage';

  _i3.Future<String?> uploadAvatar(_i9.ByteData imageData) =>
      caller.callServerEndpoint<String?>(
        'storage',
        'uploadAvatar',
        {'imageData': imageData},
      );

  _i3.Future<String?> uploadChatImage(_i9.ByteData imageData) =>
      caller.callServerEndpoint<String?>(
        'storage',
        'uploadChatImage',
        {'imageData': imageData},
      );

  _i3.Future<void> deleteAvatar() => caller.callServerEndpoint<void>(
    'storage',
    'deleteAvatar',
    {},
  );

  _i3.Future<void> deleteUserAvatar(String userId) =>
      caller.callServerEndpoint<void>(
        'storage',
        'deleteUserAvatar',
        {'userId': userId},
      );
}

/// {@category Endpoint}
class EndpointUser extends _i2.EndpointRef {
  EndpointUser(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'user';

  _i3.Future<_i7.ChatUser?> getUser({String? userId}) =>
      caller.callServerEndpoint<_i7.ChatUser?>(
        'user',
        'getUser',
        {'userId': userId},
      );

  _i3.Future<_i7.ChatUser> ensureUserExists(String email) =>
      caller.callServerEndpoint<_i7.ChatUser>(
        'user',
        'ensureUserExists',
        {'email': email},
      );

  _i3.Future<void> updateGender(int gender) => caller.callServerEndpoint<void>(
    'user',
    'updateGender',
    {'gender': gender},
  );

  _i3.Future<void> updateBirthday(DateTime birthDate) =>
      caller.callServerEndpoint<void>(
        'user',
        'updateBirthday',
        {'birthDate': birthDate},
      );

  _i3.Future<void> updateShowAge(bool showAge) =>
      caller.callServerEndpoint<void>(
        'user',
        'updateShowAge',
        {'showAge': showAge},
      );

  _i3.Future<void> updateDisplayName(
    String name,
    List<String> searchArray,
  ) => caller.callServerEndpoint<void>(
    'user',
    'updateDisplayName',
    {
      'name': name,
      'searchArray': searchArray,
    },
  );

  _i3.Future<void> updateProfileImage(
    String imageUrl,
    bool hasNudity,
  ) => caller.callServerEndpoint<void>(
    'user',
    'updateProfileImage',
    {
      'imageUrl': imageUrl,
      'hasNudity': hasNudity,
    },
  );

  _i3.Future<bool> isNameAvailable(String displayName) =>
      caller.callServerEndpoint<bool>(
        'user',
        'isNameAvailable',
        {'displayName': displayName},
      );

  _i3.Future<void> updateLocation(
    String city,
    String countryCode,
    String country,
    String regionName,
  ) => caller.callServerEndpoint<void>(
    'user',
    'updateLocation',
    {
      'city': city,
      'countryCode': countryCode,
      'country': country,
      'regionName': regionName,
    },
  );

  _i3.Future<void> setActive() => caller.callServerEndpoint<void>(
    'user',
    'setActive',
    {},
  );

  _i3.Future<void> setCurrentChatRoom(String chatId) =>
      caller.callServerEndpoint<void>(
        'user',
        'setCurrentChatRoom',
        {'chatId': chatId},
      );

  _i3.Future<void> saveFcmToken(String token) =>
      caller.callServerEndpoint<void>(
        'user',
        'saveFcmToken',
        {'token': token},
      );

  _i3.Future<void> logout() => caller.callServerEndpoint<void>(
    'user',
    'logout',
    {},
  );

  _i3.Future<void> deleteAccount() => caller.callServerEndpoint<void>(
    'user',
    'deleteAccount',
    {},
  );

  _i3.Future<void> setPremium(bool isPremium) =>
      caller.callServerEndpoint<void>(
        'user',
        'setPremium',
        {'isPremium': isPremium},
      );

  _i3.Future<void> deletePhoto() => caller.callServerEndpoint<void>(
    'user',
    'deletePhoto',
    {},
  );

  _i3.Future<void> updateImageNotReviewedStatus() =>
      caller.callServerEndpoint<void>(
        'user',
        'updateImageNotReviewedStatus',
        {},
      );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _i1.Caller(client);
    serverpod_auth_core = _i4.Caller(client);
  }

  late final _i1.Caller serverpod_auth_idp;

  late final _i4.Caller serverpod_auth_core;
}

class Client extends _i2.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    @Deprecated(
      'Use authKeyProvider instead. This will be removed in future releases.',
    )
    super.authenticationKeyManager,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _i2.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_i2.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
  }) : super(
         host,
         _i10.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
       ) {
    appleIdp = EndpointAppleIdp(this);
    googleIdp = EndpointGoogleIdp(this);
    jwtRefresh = EndpointJwtRefresh(this);
    chat = EndpointChat(this);
    messaging = EndpointMessaging(this);
    moderation = EndpointModeration(this);
    privateChat = EndpointPrivateChat(this);
    storage = EndpointStorage(this);
    user = EndpointUser(this);
    modules = Modules(this);
  }

  late final EndpointAppleIdp appleIdp;

  late final EndpointGoogleIdp googleIdp;

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointChat chat;

  late final EndpointMessaging messaging;

  late final EndpointModeration moderation;

  late final EndpointPrivateChat privateChat;

  late final EndpointStorage storage;

  late final EndpointUser user;

  late final Modules modules;

  @override
  Map<String, _i2.EndpointRef> get endpointRefLookup => {
    'appleIdp': appleIdp,
    'googleIdp': googleIdp,
    'jwtRefresh': jwtRefresh,
    'chat': chat,
    'messaging': messaging,
    'moderation': moderation,
    'privateChat': privateChat,
    'storage': storage,
    'user': user,
  };

  @override
  Map<String, _i2.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
