// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChD4747kdf9R6l5WehknJfXeTgPmUK34o',
    appId: '1:164406258776:web:fda99b951f39c6831c2e2d',
    messagingSenderId: '164406258776',
    projectId: 'chat-60225',
    authDomain: 'chat-60225.firebaseapp.com',
    databaseURL: 'https://chat-60225-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-60225.appspot.com',
    measurementId: 'G-4PRMM9Z99W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA_Ok3f2_H3bWZhKgiVzrPR6s5nYE4YKY',
    appId: '1:164406258776:android:14cc443a70f60bca1c2e2d',
    messagingSenderId: '164406258776',
    projectId: 'chat-60225',
    databaseURL: 'https://chat-60225-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-60225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYtpHeq3jcb2SSqr4Da9wC-GYfXOd6ko',
    appId: '1:164406258776:ios:9b0bee7c629721891c2e2d',
    messagingSenderId: '164406258776',
    projectId: 'chat-60225',
    databaseURL: 'https://chat-60225-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-60225.appspot.com',
    androidClientId: '164406258776-7q0513htl5ova5h4sg4e9jnq2uqugfin.apps.googleusercontent.com',
    iosClientId: '164406258776-lms93gd306frmc92vbds2o21fajlketr.apps.googleusercontent.com',
    iosBundleId: 'com.xevenition.chat',
  );
}
